from datetime import datetime, timezone
from bson import ObjectId
from app.core.database import connect_to_mongodb, get_database

def seed_verified_hospitals():
    connect_to_mongodb()
    db = get_database()
    
    # Remove test/dummy "string" records or bad entries
    db.hospitals.delete_many({
        "$or": [
            {"name": {"$regex": "^(string|test|dummy)", "$options": "i"}},
            {"city": "string"},
            {"name": "AIIMS Guntur"}
        ]
    })
    
    verified_hospitals = [
        # INDIA
        {
            "name": "All India Institute of Medical Sciences (AIIMS)",
            "city": "New Delhi",
            "state": "Delhi",
            "country": "India",
            "address": "Ansari Nagar, New Delhi, Delhi 110029",
            "phone": "+91-11-26588500",
            "website": "https://www.aiims.edu",
            "facility_type": "Government / Academic Medical Center",
            "ownership": "Government",
            "total_beds": 2478,
            "occupied_beds": 2180,
            "available_beds": 298,
            "icu_beds": 312,
            "emergency_beds": 120,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 28.5672,
            "lng": 77.2100,
            "specialties": ["Cardiology", "Neurology", "Oncology", "Pediatrics", "Trauma & Emergency", "Organ Transplant"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Apollo Hospitals Greams Road",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "address": "21 Greams Lane, Off Greams Road, Chennai, Tamil Nadu 600006",
            "phone": "+91-44-28290200",
            "website": "https://www.apollohospitals.com",
            "facility_type": "Multi-Specialty Hospital",
            "ownership": "Private / Corporate",
            "total_beds": 560,
            "occupied_beds": 472,
            "available_beds": 88,
            "icu_beds": 115,
            "emergency_beds": 45,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 13.0604,
            "lng": 80.2496,
            "specialties": ["Cardiology", "Cardiothoracic Surgery", "Oncology", "Orthopedics", "Robotic Surgery"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Tata Memorial Hospital",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "address": "Dr. E Borges Road, Parel, Mumbai, Maharashtra 400012",
            "phone": "+91-22-24177000",
            "website": "https://tmc.gov.in",
            "facility_type": "Specialized Cancer Hospital",
            "ownership": "Government / Autonomous",
            "total_beds": 700,
            "occupied_beds": 645,
            "available_beds": 55,
            "icu_beds": 90,
            "emergency_beds": 35,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 19.0068,
            "lng": 72.8427,
            "specialties": ["Radiation Oncology", "Medical Oncology", "Surgical Oncology", "Hematology", "Bone Marrow Transplant"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Manipal Hospital Old Airport Road",
            "city": "Bengaluru",
            "state": "Karnataka",
            "country": "India",
            "address": "98 HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560017",
            "phone": "+91-80-25024444",
            "website": "https://www.manipalhospitals.com",
            "facility_type": "Multi-Specialty Hospital",
            "ownership": "Private / Corporate",
            "total_beds": 600,
            "occupied_beds": 510,
            "available_beds": 90,
            "icu_beds": 120,
            "emergency_beds": 40,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.7,
            "lat": 12.9592,
            "lng": 77.6499,
            "specialties": ["Neurology", "Cardiology", "Gastroenterology", "Nephrology", "Pediatrics"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Fortis Memorial Research Institute",
            "city": "Gurugram",
            "state": "Haryana",
            "country": "India",
            "address": "Sector 44, Opposite HUDA City Centre, Gurugram, Haryana 122002",
            "phone": "+91-124-7160000",
            "website": "https://www.fortishealthcare.com",
            "facility_type": "Super-Specialty Quaternary Hospital",
            "ownership": "Private / Corporate",
            "total_beds": 400,
            "occupied_beds": 320,
            "available_beds": 80,
            "icu_beds": 85,
            "emergency_beds": 30,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 28.4595,
            "lng": 77.0726,
            "specialties": ["Robotic Surgery", "Neurosciences", "Cardiac Sciences", "Renal Sciences", "Critical Care"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Max Super Speciality Hospital Saket",
            "city": "New Delhi",
            "state": "Delhi",
            "country": "India",
            "address": "1, 2 Press Enclave Marg, Saket, New Delhi, Delhi 110017",
            "phone": "+91-11-26515050",
            "website": "https://www.maxhealthcare.in",
            "facility_type": "Super-Specialty Hospital",
            "ownership": "Private / Corporate",
            "total_beds": 530,
            "occupied_beds": 460,
            "available_beds": 70,
            "icu_beds": 110,
            "emergency_beds": 42,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 28.5283,
            "lng": 77.2114,
            "specialties": ["Cancer Care", "Cardiac Sciences", "Orthopedics", "Neurosciences", "Liver & Biliary Sciences"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Post Graduate Institute of Medical Education and Research (PGIMER)",
            "city": "Chandigarh",
            "state": "Chandigarh",
            "country": "India",
            "address": "Madhya Marg, Sector 12, Chandigarh 160012",
            "phone": "+91-172-2747585",
            "website": "https://pgimer.edu.in",
            "facility_type": "Government Tertiary Hospital",
            "ownership": "Government",
            "total_beds": 1948,
            "occupied_beds": 1780,
            "available_beds": 168,
            "icu_beds": 240,
            "emergency_beds": 95,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 30.7649,
            "lng": 76.7766,
            "specialties": ["General Medicine", "Pulmonology", "Rheumatology", "Endocrinology", "Pediatric Surgery"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Medanta - The Medicity",
            "city": "Gurugram",
            "state": "Haryana",
            "country": "India",
            "address": "CH Bakhtawar Singh Rd, Near Rajiv Chowk, Sector 38, Gurugram, Haryana 122001",
            "phone": "+91-124-4141414",
            "website": "https://www.medanta.org",
            "facility_type": "Multi-Super Specialty Institute",
            "ownership": "Private / Trust",
            "total_beds": 1250,
            "occupied_beds": 1050,
            "available_beds": 200,
            "icu_beds": 350,
            "emergency_beds": 60,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 28.4395,
            "lng": 77.0427,
            "specialties": ["Heart Institute", "Liver Transplant", "Neurosciences", "Bone & Joint", "Chest Surgery"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Christian Medical College (CMC)",
            "city": "Vellore",
            "state": "Tamil Nadu",
            "country": "India",
            "address": "Ida Scudder Road, Vellore, Tamil Nadu 632004",
            "phone": "+91-416-2281000",
            "website": "https://www.cmch-vellore.edu",
            "facility_type": "Charitable Teaching Hospital",
            "ownership": "Voluntary / Non-Profit",
            "total_beds": 3000,
            "occupied_beds": 2720,
            "available_beds": 280,
            "icu_beds": 380,
            "emergency_beds": 110,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 12.9246,
            "lng": 79.1352,
            "specialties": ["Hematology", "Gastroenterology", "Neurology", "Clinical Immunology", "Infectious Diseases"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Narayana Institute of Cardiac Sciences",
            "city": "Bengaluru",
            "state": "Karnataka",
            "country": "India",
            "address": "258/A, Bommasandra Industrial Area, Anekal Taluk, Bengaluru, Karnataka 560099",
            "phone": "+91-80-71222222",
            "website": "https://www.narayanahealth.org",
            "facility_type": "Cardiovascular Specialty Hospital",
            "ownership": "Private / Corporate",
            "total_beds": 1000,
            "occupied_beds": 820,
            "available_beds": 180,
            "icu_beds": 220,
            "emergency_beds": 50,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 12.8123,
            "lng": 77.6912,
            "specialties": ["Pediatric Cardiology", "Adult Cardiac Surgery", "Interventional Cardiology", "Electrophysiology"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        # UNITED STATES
        {
            "name": "Massachusetts General Hospital",
            "city": "Boston",
            "state": "Massachusetts",
            "country": "USA",
            "address": "55 Fruit St, Boston, MA 02114",
            "phone": "+1-617-726-2000",
            "website": "https://www.massgeneral.org",
            "facility_type": "Academic Medical Center",
            "ownership": "Voluntary Non-Profit",
            "total_beds": 1043,
            "occupied_beds": 920,
            "available_beds": 123,
            "icu_beds": 178,
            "emergency_beds": 65,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 42.3631,
            "lng": -71.0686,
            "specialties": ["Cardiology", "Neurology & Neurosurgery", "Diabetes & Endocrinology", "Cancer", "Pulmonology"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Mayo Clinic Hospital - Saint Marys Campus",
            "city": "Rochester",
            "state": "Minnesota",
            "country": "USA",
            "address": "1216 2nd St SW, Rochester, MN 55902",
            "phone": "+1-507-255-5123",
            "website": "https://www.mayoclinic.org",
            "facility_type": "Quaternary Academic Medical Center",
            "ownership": "Voluntary Non-Profit",
            "total_beds": 1265,
            "occupied_beds": 1110,
            "available_beds": 155,
            "icu_beds": 210,
            "emergency_beds": 75,
            "emergency": True,
            "has_emergency": True,
            "rating": 5.0,
            "lat": 44.0203,
            "lng": -92.4827,
            "specialties": ["Gastroenterology", "Cardiology", "Neurology", "Orthopedics", "Urology", "Cancer"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Johns Hopkins Hospital",
            "city": "Baltimore",
            "state": "Maryland",
            "country": "USA",
            "address": "1800 Orleans St, Baltimore, MD 21287",
            "phone": "+1-410-955-5000",
            "website": "https://www.hopkinsmedicine.org",
            "facility_type": "Teaching Hospital & Research Center",
            "ownership": "Voluntary Non-Profit",
            "total_beds": 1162,
            "occupied_beds": 1030,
            "available_beds": 132,
            "icu_beds": 190,
            "emergency_beds": 70,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 39.2970,
            "lng": -76.5927,
            "specialties": ["Rheumatology", "Psychiatry", "Ophthalmology", "Neurology", "Geriatrics"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Cleveland Clinic Main Campus",
            "city": "Cleveland",
            "state": "Ohio",
            "country": "USA",
            "address": "9500 Euclid Ave, Cleveland, OH 44195",
            "phone": "+1-216-444-2200",
            "website": "https://my.clevelandclinic.org",
            "facility_type": "Multi-Specialty Academic Center",
            "ownership": "Voluntary Non-Profit",
            "total_beds": 1400,
            "occupied_beds": 1260,
            "available_beds": 140,
            "icu_beds": 240,
            "emergency_beds": 80,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.9,
            "lat": 41.5034,
            "lng": -81.6214,
            "specialties": ["Heart & Vascular Institute", "Digestive Disease", "Neurological Institute", "Orthopedics"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        },
        {
            "name": "Cedars-Sinai Medical Center",
            "city": "Los Angeles",
            "state": "California",
            "country": "USA",
            "address": "8700 Beverly Blvd, Los Angeles, CA 90048",
            "phone": "+1-310-423-3277",
            "website": "https://www.cedars-sinai.org",
            "facility_type": "Tertiary Care Facility",
            "ownership": "Voluntary Non-Profit",
            "total_beds": 886,
            "occupied_beds": 790,
            "available_beds": 96,
            "icu_beds": 145,
            "emergency_beds": 55,
            "emergency": True,
            "has_emergency": True,
            "rating": 4.8,
            "lat": 34.0754,
            "lng": -118.3807,
            "specialties": ["Cardiology & Heart Surgery", "Gastroenterology", "Orthopedics", "Pulmonology", "Urology"],
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        }
    ]
    
    # Insert new verified records if not present
    for hosp in verified_hospitals:
        db.hospitals.update_one(
            {"name": hosp["name"]},
            {"$set": hosp},
            upsert=True
        )
        
    # Ensure indexes on hospitals collection
    for idx in [("name", 1), ("city", 1), ("state", 1), ("country", 1), ("emergency", 1)]:
        try:
            db.hospitals.create_index([idx])
        except Exception:
            pass
    
    print(f"Hospital database seeded successfully. Current total verified records: {db.hospitals.count_documents({})}")

if __name__ == "__main__":
    seed_verified_hospitals()
