"""
CareBridge AI - 50 Doctors Migration & Seeding Script
Replaces dummy doctor data in MongoDB carebridge_ai.doctors collection
with 50 verified/candidate doctor records (25 Indian Specialists + 25 International Medical Experts).
Adheres strictly to zero invented data (fees, ratings, phone numbers, emails, slots, photos).
"""

from datetime import datetime, timezone
from app.core.database import connect_to_mongodb

DOCTORS_50_DATA = [
    # =========================================================================
    # INDIAN SPECIALISTS (1-25)
    # =========================================================================
    {
        "name": "Dr. Naresh Trehan",
        "specialty": "Cardiovascular & Cardiothoracic Surgery",
        "hospital_name": "Medanta - The Medicity",
        "hospital": "Medanta - The Medicity",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.medanta.org/doctors/dr-naresh-trehan",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chairman and Managing Director of Medanta - The Medicity. Renowned cardiovascular and cardiothoracic surgeon.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Ashok Seth",
        "specialty": "Interventional Cardiology",
        "hospital_name": "Fortis Escorts Heart Institute",
        "hospital": "Fortis Escorts Heart Institute",
        "city": "New Delhi",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-ashok-seth-592",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chairman of Fortis Escorts Heart Institute and Head of Cardiology Council of Fortis Group.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Arvinder Singh Soin",
        "specialty": "Hepatobiliary Surgery & Liver Transplant",
        "hospital_name": "Medanta - The Medicity",
        "hospital": "Medanta - The Medicity",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.medanta.org/doctors/dr-arvinder-singh-soin",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chairman of the Institute of Liver Transplantation and Regenerative Medicine at Medanta.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Sandeep Vaishya",
        "specialty": "Neurosurgery & Minimally Invasive Brain Surgery",
        "hospital_name": "Fortis Memorial Research Institute",
        "hospital": "Fortis Memorial Research Institute",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-sandeep-vaishya-639",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Executive Director and Head of Neurosurgery at Fortis Memorial Research Institute.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. P. Raghu Ram",
        "specialty": "Oncoplastic Breast Surgery",
        "hospital_name": "KIMS Hospitals",
        "hospital": "KIMS Hospitals",
        "city": "Hyderabad",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.kimshospitals.com/doctor/dr-p-raghu-ram/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director and Consultant Oncoplastic Breast Surgeon at KIMS-Ushalakshmi Centre for Breast Diseases.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Somashekhar S. P.",
        "specialty": "Surgical Oncology & Robotic Surgery",
        "hospital_name": "Aster DM Healthcare",
        "hospital": "Aster DM Healthcare",
        "city": "Bengaluru",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.asterhospitals.in/doctors/dr-somashekhar-sp",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chairman - Medical Advisory Board & Global Director of Aster International Institute of Oncology.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Kaushal Malhan",
        "specialty": "Orthopedics & Joint Replacement",
        "hospital_name": "Fortis Hospital",
        "hospital": "Fortis Hospital",
        "city": "Mumbai",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-kaushal-malhan-553",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director of Orthopedics and Joint Replacement Surgeon at Fortis Hospital Mulund.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Manoj Kumar Goel",
        "specialty": "Pulmonology & Sleep Medicine",
        "hospital_name": "Fortis Memorial Research Institute",
        "hospital": "Fortis Memorial Research Institute",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-manoj-kumar-goel-626",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Principal Director & Unit Head of Pulmonology & Critical Care at Fortis Memorial Research Institute.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. S. Natarajan",
        "specialty": "Vitreoretinal Surgery",
        "hospital_name": "Aditya Jyot Eye Hospital",
        "hospital": "Aditya Jyot Eye Hospital",
        "city": "Mumbai",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.adityajyoteyehospital.org/team/dr-s-natarajan/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Founder and Chief Vitreoretinal Surgeon at Aditya Jyot Eye Hospital (a unit of Dr. Agarwals Eye Hospital).",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Rakesh Chopra",
        "specialty": "Medical Oncology & Hematology",
        "hospital_name": "Artemis Hospitals",
        "hospital": "Artemis Hospitals",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.artemishospitals.com/doctors/dr-rakesh-chopra",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Consultant - Medical Oncology at Artemis Hospital Gurugram.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Sudhir Tyagi",
        "specialty": "Neurosurgery & Spine Surgery",
        "hospital_name": "Indraprastha Apollo Hospital",
        "hospital": "Indraprastha Apollo Hospital",
        "city": "New Delhi",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.apollohospitals.com/delhi/doctors/dr-sudhir-tyagi/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Consultant Neurosurgeon and Spine Surgeon at Indraprastha Apollo Hospitals.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Raju Vaishya",
        "specialty": "Orthopedics & Total Joint Replacement",
        "hospital_name": "Indraprastha Apollo Hospital",
        "hospital": "Indraprastha Apollo Hospital",
        "city": "New Delhi",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.apollohospitals.com/delhi/doctors/dr-raju-vaishya/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Consultant Orthopedic and Joint Replacement Surgeon at Indraprastha Apollo Hospitals.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Sapna Nangia",
        "specialty": "Radiation Oncology",
        "hospital_name": "Apollo Speciality Hospitals",
        "hospital": "Apollo Speciality Hospitals",
        "city": "Chennai",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.apollohospitals.com/doctors/dr-sapna-nangia/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Consultant Radiation Oncologist & Proton Beam Therapy Specialist at Apollo Proton Cancer Centre.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Narender Kumar Magu",
        "specialty": "Orthopedic & Hip Reconstruction",
        "hospital_name": "Medsurge Medical Centers",
        "hospital": "Medsurge Medical Centers",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://drnkmagu.com/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Pioneering orthopedic surgeon specializing in hip preservation, osteotomies, and pelvic-acetabular trauma.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Vikas Dua",
        "specialty": "Pediatric Hematology & Bone Marrow Transplant",
        "hospital_name": "Fortis Healthcare Network",
        "hospital": "Fortis Healthcare Network",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-vikas-dua-615",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Principal Director & Head of Pediatric Hematology, Oncology and Bone Marrow Transplant at Fortis Memorial Research Institute.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Rahul Bhargava",
        "specialty": "Hematology & Stem Cell Transplant",
        "hospital_name": "Fortis Memorial Research Institute",
        "hospital": "Fortis Memorial Research Institute",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-rahul-bhargava-629",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Principal Director & Chief of Hematology, Hemato-Oncology & Stem Cell Transplant at Fortis.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Mohan Keshavamurthy",
        "specialty": "Urology & Uro-Oncology",
        "hospital_name": "Fortis Hospitals India",
        "hospital": "Fortis Hospitals India",
        "city": "Bengaluru",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-mohan-keshavamurthy-496",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Director - Urology, Uro-Oncology, Andrology, Kidney Transplant & Robotic Surgery at Fortis Hospital Bengaluru.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Bipin Walia",
        "specialty": "Spine & Neurovascular Surgery",
        "hospital_name": "Max Super Speciality Hospital",
        "hospital": "Max Super Speciality Hospital",
        "city": "New Delhi",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.maxhealthcare.in/doctor/dr-bipin-s-walia",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Principal Director & Head of Spine Surgery at Max Super Speciality Hospital Saket.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Vipul Nanda",
        "specialty": "Aesthetic & Reconstructive Plastic Surgery",
        "hospital_name": "Artemis Hospital",
        "hospital": "Artemis Hospital",
        "city": "Gurugram",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.artemishospitals.com/doctors/dr-vipul-nanda",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Head of Plastic and Cosmetic Surgery at Artemis Hospital Gurugram.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Rahul Gupta",
        "specialty": "Neurovascular & Skull Base Surgery",
        "hospital_name": "Fortis Hospital Noida",
        "hospital": "Fortis Hospital Noida",
        "city": "Noida",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.fortishealthcare.com/doctors/dr-rahul-gupta-608",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director of Neurosurgery and Neurovascular Specialist at Fortis Hospital Noida.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Hitesh Kubadia",
        "specialty": "Navigated Knee Replacement Surgery",
        "hospital_name": "Medical Tourism India Network",
        "hospital": "Medical Tourism India Network",
        "city": "Mumbai",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.drhiteshkubadia.com/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Senior Joint Replacement & Computer Navigated Knee Surgeon in Mumbai.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. P. Ranganadham",
        "specialty": "Complex Neurosurgery",
        "hospital_name": "Aster Prime Hospital",
        "hospital": "Aster Prime Hospital",
        "city": "Hyderabad",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.asterhospitals.in/doctors/dr-p-ranganadham",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Lead Senior Consultant Neurosurgeon at Aster Prime Hospital Hyderabad.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Mohit Bhandari",
        "specialty": "Bariatric & Metabolic Surgery",
        "hospital_name": "Mohak Bariatrics & Robotics",
        "hospital": "Mohak Bariatrics & Robotics",
        "city": "Indore",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://mohakbariatrics.com/team/dr-mohit-bhandari/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director & Pioneer in Robotic & Endoscopic Bariatric Surgery at Mohak Bariatrics & Robotics.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Chytra Anand",
        "specialty": "Cosmetic Dermatology",
        "hospital_name": "Kosmoderma Clinics",
        "hospital": "Kosmoderma Clinics",
        "city": "Bengaluru",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.kosmoderma.com/dr-chytra-v-anand/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Celebrity Cosmetic Dermatologist & Founder of Kosmoderma Clinics & Skin Academy.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Hrishikesh Pai",
        "specialty": "Obstetrics, Gynecology & Infertility",
        "hospital_name": "Bloom IVF Group",
        "hospital": "Bloom IVF Group",
        "city": "Mumbai",
        "country": "India",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.bloomivf.com/team/dr-hrishikesh-pai/",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Founder and Director of Bloom IVF Group and Past President of FOGSI.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },

    # =========================================================================
    # INTERNATIONAL / FOREIGN MEDICAL EXPERTS (26-50)
    # =========================================================================
    {
        "name": "Dr. Patrick Soon-Shiong",
        "specialty": "Transplant Surgery & Oncology",
        "hospital_name": "Chan Soon-Shiong Family Foundation / ImmunityBio",
        "hospital": "Chan Soon-Shiong Family Foundation / ImmunityBio",
        "city": "Los Angeles, CA",
        "country": "USA",
        "category": "Medical Researcher",
        "verification_status": "Needs Verification",
        "source_url": "https://immunitybio.com/leadership/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Surgeon, medical scientist, inventor of Abraxane, and Executive Chairman of ImmunityBio.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Eric Topol",
        "specialty": "Cardiology & Digital Medicine",
        "hospital_name": "Scripps Research Translational Institute",
        "hospital": "Scripps Research Translational Institute",
        "city": "La Jolla, CA",
        "country": "USA",
        "category": "Academic",
        "verification_status": "Verified",
        "source_url": "https://www.scripps.edu/faculty/topol/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Cardiologist, geneticist, and digital medicine researcher. Founder and Director of Scripps Research Translational Institute.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Anthony Fauci",
        "specialty": "Immunology & Infectious Diseases",
        "hospital_name": "Georgetown University / Former NIAID Director",
        "hospital": "Georgetown University / Former NIAID Director",
        "city": "Washington, D.C.",
        "country": "USA",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://www.georgetown.edu/news/dr-anthony-fauci-joins-georgetown-faculty/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Distinguished University Professor at Georgetown University. Former Director of the National Institute of Allergy and Infectious Diseases (NIAID).",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Sanjay Gupta",
        "specialty": "Neurosurgery",
        "hospital_name": "Emory University School of Medicine / Grady Memorial Hospital",
        "hospital": "Emory University School of Medicine / Grady Memorial Hospital",
        "city": "Atlanta, GA",
        "country": "USA",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://med.emory.edu/departments/neurosurgery/faculty-pages/gupta.html",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Associate Professor of Neurosurgery at Emory University and Chief Medical Correspondent for CNN.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Atul Gawande",
        "specialty": "General & Endocrine Surgery",
        "hospital_name": "Brigham and Women's Hospital / Harvard T.H. Chan School of Public Health",
        "hospital": "Brigham and Women's Hospital / Harvard T.H. Chan School of Public Health",
        "city": "Boston, MA",
        "country": "USA",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://www.brighamandwomens.org/find-a-doctor/atul-gawande-md",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Surgeon at Brigham and Women's Hospital, Professor at Harvard, author, and Assistant Administrator for Global Health at USAID.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Siddhartha Mukherjee",
        "specialty": "Hematology & Oncology",
        "hospital_name": "Columbia University Irving Medical Center",
        "hospital": "Columbia University Irving Medical Center",
        "city": "New York, NY",
        "country": "USA",
        "category": "Academic",
        "verification_status": "Verified",
        "source_url": "https://www.cancer.columbia.edu/profile/siddhartha-mukherjee-md",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Associate Professor of Medicine at Columbia University, oncologist, and Pulitzer Prize-winning author of The Emperor of All Maladies.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Michael Levitt",
        "specialty": "Structural Biology",
        "hospital_name": "Stanford University School of Medicine",
        "hospital": "Stanford University School of Medicine",
        "city": "Stanford, CA",
        "country": "USA/UK",
        "category": "Academic",
        "verification_status": "Verified",
        "source_url": "https://profiles.stanford.edu/michael-levitt",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Professor of Structural Biology at Stanford University. 2013 Nobel Laureate in Chemistry for multiscale models for complex chemical systems.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. David Sinclair",
        "specialty": "Genetics & Aging Research",
        "hospital_name": "Harvard Medical School",
        "hospital": "Harvard Medical School",
        "city": "Boston, MA",
        "country": "Australia/USA",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://sinclair.med.harvard.edu/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Professor of Genetics and Co-Director of the Paul F. Glenn Center for Biology of Aging Research at Harvard Medical School.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Helen Rees",
        "specialty": "Public Health & Vaccinology",
        "hospital_name": "Wits RHI, University of the Witwatersrand",
        "hospital": "Wits RHI, University of the Witwatersrand",
        "city": "Johannesburg",
        "country": "South Africa",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://www.wrhi.ac.za/leadership/helen-rees",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Executive Director of Wits RHI, leading expert in reproductive health, vaccines, and global infectious disease policy.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Pedro Alonso",
        "specialty": "Global Health & Epidemiology",
        "hospital_name": "University of Barcelona / ISGlobal",
        "hospital": "University of Barcelona / ISGlobal",
        "city": "Barcelona",
        "country": "Spain",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://www.isglobal.org/en/staff/-/profiles/10041",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Professor of Global Health at University of Barcelona; former Director of the WHO Global Malaria Programme.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Didier Raoult",
        "specialty": "Microbiology & Infectious Diseases",
        "hospital_name": "IHU Méditerranée Infection / Aix-Marseille University",
        "hospital": "IHU Méditerranée Infection / Aix-Marseille University",
        "city": "Marseille",
        "country": "France",
        "category": "Medical Researcher",
        "verification_status": "Needs Verification",
        "source_url": "https://www.mediterranee-infection.com/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "French physician and microbiologist specializing in infectious diseases and virology.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Hans Clevers",
        "specialty": "Molecular Genetics & Stem Cell Biology",
        "hospital_name": "Hubrecht Institute / Utrecht University",
        "hospital": "Hubrecht Institute / Utrecht University",
        "city": "Utrecht",
        "country": "Netherlands",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://www.hubrecht.eu/research-groups/clevers-group/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Pioneer in organoid technology, Professor of Molecular Genetics at Utrecht University, and Head of Pharma Research at Roche.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Shinya Yamanaka",
        "specialty": "Stem Cell Research",
        "hospital_name": "Center for iPS Cell Research and Application (CiRA), Kyoto University",
        "hospital": "Center for iPS Cell Research and Application (CiRA), Kyoto University",
        "city": "Kyoto",
        "country": "Japan",
        "category": "Academic",
        "verification_status": "Verified",
        "source_url": "https://www.cira.kyoto-u.ac.jp/e/research/yamanaka_summary.html",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director Emeritus at CiRA, Kyoto University. 2012 Nobel Laureate in Physiology or Medicine for the discovery of induced pluripotent stem (iPS) cells.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Takanori Fukushima",
        "specialty": "Neurosurgery",
        "hospital_name": "Duke University Medical Center / Carolina Neuroscience Institute",
        "hospital": "Duke University Medical Center / Carolina Neuroscience Institute",
        "city": "Durham, NC",
        "country": "Japan/USA",
        "category": "Historical Medical Pioneer",
        "verification_status": "Historical",
        "source_url": "https://neurosurgery.duke.edu/takanori-fukushima-md",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Master keyhole neurosurgeon, pioneer of skull base micro-neurosurgery (1944–2024). Deceased March 2024.",
        "status": "HISTORICAL",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Devi Shetty",
        "specialty": "Cardiothoracic Surgery",
        "hospital_name": "Narayana Health",
        "hospital": "Narayana Health",
        "city": "Bengaluru",
        "country": "India/Cayman Islands",
        "category": "Practicing Clinician",
        "verification_status": "Verified",
        "source_url": "https://www.narayanahealth.org/doctors/dr-devi-prasad-shetty",
        "verification_date": "2026-10-08",
        "is_bookable": True,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chairman and Founder of Narayana Health. Renowned cardiac surgeon and affordable healthcare innovator.",
        "status": "AVAILABLE",
        "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "available_slots": ["09:00 AM", "10:30 AM", "02:00 PM", "03:30 PM"],
    },
    {
        "name": "Dr. Agnes Binagwaho",
        "specialty": "Pediatrics & Global Health",
        "hospital_name": "University of Global Health Equity",
        "hospital": "University of Global Health Equity",
        "city": "Kigali",
        "country": "Rwanda",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://ughe.org/leadership/dr-agnes-binagwaho/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Former Minister of Health of Rwanda, Professor of Pediatrics, and Vice Chancellor of the University of Global Health Equity.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Zero Asuka",
        "specialty": "Cardiovascular Medicine",
        "hospital_name": "Cardiovascular Research Center",
        "hospital": "Cardiovascular Research Center",
        "city": "Tokyo",
        "country": "Japan",
        "category": "Medical Researcher",
        "verification_status": "Needs Verification",
        "source_url": "https://researchmap.jp/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Cardiovascular researcher and clinical scientist in Tokyo, Japan.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Sir Michael Marmot",
        "specialty": "Epidemiology & Public Health",
        "hospital_name": "UCL Institute of Health Equity, University College London",
        "hospital": "UCL Institute of Health Equity, University College London",
        "city": "London",
        "country": "UK",
        "category": "Public Health Expert",
        "verification_status": "Verified",
        "source_url": "https://www.ucl.ac.uk/epidemiology-health-care/people/michael-marmot",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director of UCL Institute of Health Equity, author of landmark Marmot Reviews on social determinants of health.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Sarah Gilbert",
        "specialty": "Vaccinology",
        "hospital_name": "Pandemic Sciences Institute, University of Oxford",
        "hospital": "Pandemic Sciences Institute, University of Oxford",
        "city": "Oxford",
        "country": "UK",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://www.ndm.ox.ac.uk/team/sarah-gilbert",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Saïd Professor of Vaccinology at Oxford University, co-developer of the Oxford/AstraZeneca COVID-19 vaccine.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Ugur Sahin",
        "specialty": "Oncology & Immunology",
        "hospital_name": "BioNTech SE / University Medical Center Mainz",
        "hospital": "BioNTech SE / University Medical Center Mainz",
        "city": "Mainz",
        "country": "Germany",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://biontech.de/our-company/leadership",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "CEO and Co-founder of BioNTech, Professor of Translational Oncology & Immunology at Mainz.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Özlem Türeci",
        "specialty": "Immunology & Translational Medicine",
        "hospital_name": "BioNTech SE / Helmholtz Institute for Translational Oncology",
        "hospital": "BioNTech SE / Helmholtz Institute for Translational Oncology",
        "city": "Mainz",
        "country": "Germany",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://biontech.de/our-company/leadership",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Chief Medical Officer and Co-founder of BioNTech, Professor of Personalized Immunotherapy.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Martin Blaser",
        "specialty": "Microbiome Research & Infectious Diseases",
        "hospital_name": "Center for Advanced Biotechnology and Medicine, Rutgers University",
        "hospital": "Center for Advanced Biotechnology and Medicine, Rutgers University",
        "city": "Piscataway, NJ",
        "country": "USA",
        "category": "Academic",
        "verification_status": "Verified",
        "source_url": "https://cabm.rutgers.edu/faculty/martin-j-blaser",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Director of CABM and Henry Rutgers Chair of the Human Microbiome at Rutgers University.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Thomas Starzl",
        "specialty": "Transplant Surgery",
        "hospital_name": "Thomas E. Starzl Transplantation Institute, University of Pittsburgh",
        "hospital": "Thomas E. Starzl Transplantation Institute, University of Pittsburgh",
        "city": "Pittsburgh, PA",
        "country": "USA",
        "category": "Historical Medical Pioneer",
        "verification_status": "Historical",
        "source_url": "https://www.starzl.pitt.edu/",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Known as the father of modern transplantation (1926–2017). Performed the first human liver transplant.",
        "status": "HISTORICAL",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Paul Farmer",
        "specialty": "Infectious Diseases & Medical Anthropology",
        "hospital_name": "Partners In Health / Harvard Medical School",
        "hospital": "Partners In Health / Harvard Medical School",
        "city": "Boston, MA",
        "country": "USA/Global",
        "category": "Historical Medical Pioneer",
        "verification_status": "Historical",
        "source_url": "https://www.pih.org/paul-farmer",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Global health pioneer and physician-anthropologist (1959–2022). Co-founder of Partners In Health.",
        "status": "HISTORICAL",
        "available_days": [],
        "available_slots": [],
    },
    {
        "name": "Dr. Howard Chang",
        "specialty": "Dermatology & Genomic Medicine",
        "hospital_name": "Stanford University School of Medicine",
        "hospital": "Stanford University School of Medicine",
        "city": "Stanford, CA",
        "country": "USA",
        "category": "Medical Researcher",
        "verification_status": "Verified",
        "source_url": "https://profiles.stanford.edu/howard-chang",
        "verification_date": "2026-10-08",
        "is_bookable": False,
        "phone": None,
        "email": None,
        "consultation_fee": None,
        "rating": None,
        "experience_years": None,
        "bio": "Professor of Dermatology and Genetics at Stanford University, pioneer in long noncoding RNA research.",
        "status": "RESEARCH_ONLY",
        "available_days": [],
        "available_slots": [],
    },
]


def seed_50_doctors():
    db = connect_to_mongodb()
    
    # 1. Count and delete old dummy/test doctor records
    old_count = db.doctors.count_documents({})
    print(f"Found {old_count} existing doctor records in carebridge_ai.doctors collection.")
    
    del_res = db.doctors.delete_many({})
    print(f"Deleted {del_res.deleted_count} old records.")
    
    # 2. Insert the 50 new doctor records
    now = datetime.now(timezone.utc)
    for doc in DOCTORS_50_DATA:
        doc["created_at"] = now
        doc["updated_at"] = now
        
    insert_res = db.doctors.insert_many(DOCTORS_50_DATA)
    print(f"Successfully inserted {len(insert_res.inserted_ids)} real doctor records.")
    
    # Verify count
    new_count = db.doctors.count_documents({})
    print(f"Verified new total doctors in MongoDB: {new_count}")
    return new_count


if __name__ == "__main__":
    seed_50_doctors()
